"""update users table with last seen

Revision ID: 354155f3c5b6
Revises: 0f688a682015
Create Date: 2018-11-27 14:54:44.343394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354155f3c5b6'
down_revision = '0f688a682015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
